version: '3.5'

services:

  nginx:
    image: nginx
    restart: always
    hostname: nginx
    container_name: nginx
    privileged: true
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/www/:/usr/share/nginx/html/
      - ./docker/nginx/logs/:/var/log/nginx/
    networks:
      - moos_network
  
  # mysql:
  #   # 镜像名
  #   image: mysql:8.0.21
  #   # 容器名(以后的控制都通过这个)
  #   container_name: rcs_mysql8.0
  #   privileged: true
  #   # 重启策略
  #   restart: always
  #   environment:
  #     # 时区上海
  #     TZ: Asia/Shanghai
  #     # root 密码
  #     MYSQL_ROOT_PASSWORD: Galaxis_rcs2023
  #     # 初始化数据库(后续的初始化sql会在这个库执行)
  #     MYSQL_DATABASE: rcs
  #     # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
  #     MYSQL_USER: rcs
  #     # 用户密码
  #     MYSQL_PASSWORD: Galaxis_rcs2023
  #     # 映射端口
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     # 数据挂载 首次挂载清除宿主机的 data目录
  #     # - ./rcs3_docker/mysql/data/:/var/lib/mysql/
  #     # 配置挂载
  #     - ./rcs3_docker/mysql/conf/:/etc/mysql/conf.d
  #     - ./rcs3_docker/mysql/init/:/docker-entrypoint-initdb.d/
  #       #- ./rcs3_docker/mysql/logs/:/logs/
  #   command:
  #     # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
  #     --default-authentication-plugin=mysql_native_password
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --explicit_defaults_for_timestamp=true
  #     #--lower_case_table_names=1
  #   networks:
  #     - moos_network
  
networks:
  moos_network:
    driver: bridge
